Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
 
  config.vm.define "web" do |web|
    web.vm.box = "apache/trusty64"
  end
 
  config.vm.define "db" do |db|
    db.vm.box = "mysql/trusty64"
  end
end