---
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CLI_ARGS= #optional
    volumes:
      - /opt/duplicati/config:/config
      - /opt/duplicati/backup:/backups
      - /home:/source
      - /bin:/source
    ports:
      - 8200:8200
    restart: unless-stopped
