---
  - name: Deploy GitLab Runner
    hosts: Linux2

    tasks:
      
      - name: Add the official GitLab repository
        become: True
        shell:
          cmd: "curl -L 'https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh' | sudo bash"
          chdir: /root/
     
      - name: Install the latest version of GitLab Runner
        apt:
          name: "gitlab-runner"
          state: latest

      - name: install python-gitlab
        pip:
          name: "python-gitlab"
          state: latest

      - name: "Register GitLab runner"
        community.general.gitlab_runner:
          api_url: https://gitlab.com//
          api_token: 
          registration_token:
          description: Shell Runner
          state: present
          active: true
          tag_list: ['test']
          run_untagged: false
          locked: false