version: '3'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "/~/nginx/conf:/etc/nginx"
    - "~/nginx/logs:/var/log/nginx"
    - "~/nginx/www:/usr/share/nginx/html"
    - "~/nginx/sites:/sites"

